<a href="https://colab.research.google.com/github/amitpad/PHYS247/blob/master/Assignemnt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pylab as plt

In [0]:
import numpy as np

In [0]:
D = np.array([[1.72,0.1],[-0.58,0.31],[1.99,1.54],[1.60,4.97],[2.72,2.43],[2.83,3.59],[5.95,7.71],[4.75,7.63],[5.57,5.60],[9.82,7.91]])
D

array([[ 1.72,  0.1 ],
       [-0.58,  0.31],
       [ 1.99,  1.54],
       [ 1.6 ,  4.97],
       [ 2.72,  2.43],
       [ 2.83,  3.59],
       [ 5.95,  7.71],
       [ 4.75,  7.63],
       [ 5.57,  5.6 ],
       [ 9.82,  7.91]])

In [0]:
coVar = np.cov(np.transpose(D))
coVar

array([[8.70742333, 7.41923   ],
       [7.41923   , 9.21336556]])

In [0]:
E=np.linalg.eig(coVar1)
E

(array([ 1.53685296, 16.38393593]), array([[-0.71905385, -0.69495436],
        [ 0.69495436, -0.71905385]]))

In [0]:
#Second eigenvalue (16.3839) is higher due to which selecting the second vector in the array
SF=E[1].T[1]
SF

array([-0.69495436, -0.71905385])

In [0]:
P = np.dot(D,SF)

In [0]:
print('Final 1-D dataset after PCA is ',P)

Final 1-D dataset after PCA is  [ -1.26722688   0.18016683  -2.4903021   -4.68562461  -3.63757671
  -4.54812416  -9.67888362  -8.78741408  -7.89759734 -12.51216776]
